# version: "3.9"
# services:
#   web:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       DATABASE_URL: "file:./dev.db" # Base de données SQLite
#     volumes:
#       - ./dev.db:/app/dev.db
#     command: sh -c "npx prisma migrate deploy && npm start"


version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://ordian:mI2mona.@35.195.147.151:5432/my_database
    volumes:
      - ./dev.db:/app/dev.db
    command: sh -c "npx prisma migrate deploy && npm start"
