# name: Deploy to GCP

# on:
#   push:
#     branches:
#       # - main  # Le workflow se déclenche sur chaque push vers la branche `main`
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Google Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           version: 'latest'
#           service_account_key: ${{ secrets.GCP_CREDENTIALS }}
#           project_id: silver-harmony-449206-p9

#       - name: Authenticate Docker with Artifact Registry
#         run: gcloud auth configure-docker europe-west9-docker.pkg.dev

#       - name: Build and push Docker image
#         run: |
#           docker build \
#             --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
#             --build-arg CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
#             --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
#             --build-arg NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
#             --build-arg NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }} \
#             -t europe-west9-docker.pkg.dev/silver-harmony-449206-p9/githubsactions/my-nextjs-app:prod-latest .
          
#           docker push europe-west9-docker.pkg.dev/silver-harmony-449206-p9/githubsactions/my-nextjs-app:prod-latest

#       - name: Deploy to Google Compute Engine
#         run: |
#           gcloud compute instances delete my-nextjs-instance --zone=europe-west1-d --quiet || true
#           gcloud compute instances create-with-container my-nextjs-instance \
#             --zone=europe-west1-d \
#             --container-image=europe-west9-docker.pkg.dev/silver-harmony-449206-p9/githubsactions/my-nextjs-app:prod-latest \
#             --container-restart-policy=always \
#             --container-env="NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }},CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }},DATABASE_URL=${{ secrets.DATABASE_URL }},NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }},NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}" \
#             --tags=http-server,https-server \
#             --boot-disk-size=50GB


name: Deploy to GCP

on:
  push:
    branches:
      - master  # Déclencher le workflow sur chaque push vers la branche `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: silver-harmony-449206-p9

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
            --build-arg CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }} \
            -t europe-west9-docker.pkg.dev/silver-harmony-449206-p9/githubsactions/my-nextjs-app:prod-latest .
          
          docker push europe-west9-docker.pkg.dev/silver-harmony-449206-p9/githubsactions/my-nextjs-app:prod-latest

      - name: Deploy to Google Compute Engine
        run: |
          gcloud compute instances delete my-nextjs-instance --zone=europe-west1-d --quiet || true
          gcloud compute instances create-with-container my-nextjs-instance \
            --zone=europe-west1-d \
            --container-image=europe-west9-docker.pkg.dev/silver-harmony-449206-p9/githubsactions/my-nextjs-app:prod-latest \
            --container-restart-policy=always \
            --container-env="NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }},CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }},DATABASE_URL=${{ secrets.DATABASE_URL }},NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }},NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}" \
            --tags=http-server,https-server \
            --boot-disk-size=50GB
